package com.yuhubs.ms.security;

import org.springframework.context.EnvironmentAware;
import org.springframework.core.env.Environment;

public class SecurityProperties implements EnvironmentAware {

	public static final String JWT_TOKEN_SECRET_KEY = "yuhubs.ms.security.jwt.key";

	// Generated by: head -c 16 /dev/urandom | od -An -t x | tr -d ' '
	private static final String DEFAULT_JWT_TOKEN_SECRET_KEY =
			"3bfcb44406fb65e79d77c8ea6b1fef19";


	public static final String JWT_TOKEN_EXPIRATION = "yuhubs.ms.security.jwt.expiration";

	private static final int ONE_DAY_MINUTES = 24 * 60;


	private Environment environment;


	@Override
	public void setEnvironment(Environment environment) {
		this.environment = environment;
	}

	public Environment getEnvironment() {
		return environment;
	}

	public String getJwtTokenSecretKey() {
		return environment.getProperty(JWT_TOKEN_SECRET_KEY, DEFAULT_JWT_TOKEN_SECRET_KEY);
	}

	public int getJwtTokenExpiration() {
		String exp = environment.getProperty(JWT_TOKEN_EXPIRATION);
		if (exp != null) {
			return Integer.parseInt(exp);
		}
		return ONE_DAY_MINUTES;
	}

}
